[tool.poetry]
name = "spotify-classification"
version = "0.1.0"
description = "Aplikasi Streamlit untuk klasifikasi popularitas lagu Spotify"
authors = ["Rama Majid"]
readme = "README.md"

# 🔴 WAJIB untuk Streamlit
package-mode = false


[tool.poetry.dependencies]
python = "^3.11"

# Core
streamlit = "^1.32.0"
pandas = "^2.1.0"
numpy = "^1.26.0"
joblib = "*"

# Plotting & Visualization
plotly = "^5.18.0"
matplotlib = "*"
seaborn = "*"

# Machine Learning
scikit-learn = "^1.3.0"

# Deep Learning
tensorflow = "^2.15.0"
torch = "*"
pytorch-tabnet = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
