[tool.poetry]
name = "spotify-classification"
version = "0.1.0"
description = "Aplikasi Streamlit untuk klasifikasi popularitas lagu Spotify"
authors = ["Rama Majid"]
readme = "README.md"

# 🔴 PENTING: Nonaktifkan packaging mode
# Karena ini aplikasi Streamlit, bukan Python library
package-mode = false


[tool.poetry.dependencies]
python = "^3.11"

# Core
streamlit = "^1.32.0"
numpy = "^1.26.0"
pandas = "^2.1.0"
scikit-learn = "^1.3.0"
joblib = "*"

# Visualisasi
plotly = "^5.18.0"
matplotlib = "*"
seaborn = "*"

# Deep Learning / ML
torch = "*"
tensorflow = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
